// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'core/network/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: Env.firebaseWebApiKey,
    appId: '1:1099392878008:web:d348e475fefe8645e2fb4d',
    messagingSenderId: '1099392878008',
    projectId: 'smartbank-ai-c784d',
    authDomain: 'smartbank-ai-c784d.firebaseapp.com',
    storageBucket: 'smartbank-ai-c784d.firebasestorage.app',
    measurementId: 'G-SR5VSCK6GR',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: Env.firebaseAndroidApiKey,
    appId: '1:1099392878008:android:82db1abdb4c0a69fe2fb4d',
    messagingSenderId: '1099392878008',
    projectId: 'smartbank-ai-c784d',
    storageBucket: 'smartbank-ai-c784d.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.firebaseIosApiKey,
    appId: '1:1099392878008:ios:f816cf70818e0970e2fb4d',
    messagingSenderId: '1099392878008',
    projectId: 'smartbank-ai-c784d',
    storageBucket: 'smartbank-ai-c784d.firebasestorage.app',
    iosClientId: '1099392878008-4e55haob88afm0c5qr8ta24bnb40bhtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiBanking',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: Env.firebaseMacosApiKey,
    appId: '1:1099392878008:ios:f816cf70818e0970e2fb4d',
    messagingSenderId: '1099392878008',
    projectId: 'smartbank-ai-c784d',
    storageBucket: 'smartbank-ai-c784d.firebasestorage.app',
    iosClientId: '1099392878008-4e55haob88afm0c5qr8ta24bnb40bhtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiBanking',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: Env.firebaseWindowsApiKey,
    appId: '1:1099392878008:web:1570f2de287d3cdce2fb4d',
    messagingSenderId: '1099392878008',
    projectId: 'smartbank-ai-c784d',
    authDomain: 'smartbank-ai-c784d.firebaseapp.com',
    storageBucket: 'smartbank-ai-c784d.firebasestorage.app',
    measurementId: 'G-N5GLS1D81V',
  );
}
